# Generated by Django 5.1.15 on 2026-10-06 14:24

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.uploads.UniqueUploadTo('shops/logos')),
        ),
    ]
