# Generated by Django 5.1.15 on 2026-10-06 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_shop_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='accent_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a color as #rrggbb.')]),
        ),
        migrations.AddField(
            model_name='shop',
            name='primary_color',
            field=models.CharField(blank=True, default='', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a color as #rrggbb.')]),
        ),
    ]
