# Generated by Django 5.1.15 on 2026-10-07 14:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0003_shop_theme_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='commission_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))]),
        ),
        migrations.AddField(
            model_name='shop',
            name='payout_account_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='shop',
            name='payout_network',
            field=models.CharField(blank=True, choices=[('MPESA', 'M-Pesa'), ('TIGOPESA', 'Tigo Pesa'), ('AIRTEL', 'Airtel Money'), ('HALOPESA', 'HaloPesa')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='payout_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
