# Generated by Django 5.1.15 on 2026-10-06 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_orderitem_status_orderitemstatusevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='rider',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'RIDER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deliveries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='rider_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
