# Generated by Django 5.1.15 on 2026-10-07 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        ('orders', '0003_orderitem_rider_orderitem_rider_assigned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='commission_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='commission_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='payout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='finance.payout'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='vendor_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
