# Generated by Django 5.1.15 on 2026-10-06 14:42

import apps.core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=apps.core.uploads.UniqueUploadTo('products')),
        ),
    ]
