# Generated by Django 5.1.15 on 2026-10-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_is_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('VENDOR', 'Vendor'), ('ADMINISTRATOR', 'Administrator'), ('RIDER', 'Rider')], max_length=20),
        ),
    ]
